### ISSUE TITLE
Minetest developper italia

### ISSUE THREAD

**Issue by pandaro** [H4mlet/hamlets_quest#1]
Ciao sono sempre pandaro, suggerisco di comunicare e progettare quì, e di utilizzre irch per le comunicazioni rapide. 
canale irch: #minetestitalia

**Comment by H4mlet** [comment]
ok, #minetest-ita l'ho registrato io tempo fa

**Comment by pandaro** [comment]
ora io volevo continuare le discussioni sul server-game-community italiana in un posto diverso dal forum perchè:
1. il dibattito sembra meno diretto a tutta la comunità, in realtà credo che sia meglio non fomentare l'interesse di chi non ha tempo e capacità da dedicare.
2.quì possiamo aprire e chiudere e gestire discussioni in maniera molto più sistematica
3. github è fatto apposta per chi sviluppa

Per fare ciò sarebbe opportuno avere:
1. un progetto github dedicato, credo che dovrebbe essere chi hosta il server(carl) a detenerlo, noi lo forkiamo e creiamo PR.
2. un canale di comunicazione rapida su irch mminetestitalia appunto
